In [39]:
from moexalgo import Market, Ticker

import pandas as pd
import numpy as np

from datetime import datetime

In [72]:
tradestats = pd.DataFrame()
obstats = pd.DataFrame()
orderbook = pd.DataFrame()

for ticker_name in ['AFLT', 'BANE', 'DSKY', 'FEES', 'GAZP', 'PHOR', 'POSI', 'SBER', 'YNDX', 'MTLR']:
    ticker = Ticker(ticker_name)
    
    t = ticker.tradestats(date='2023-11-01', till_date='2023-11-30')
    t.drop(columns='systime', inplace=True)
    tradestats = pd.concat([tradestats, t])

    obs = ticker.obstats(date='2023-11-01', till_date='2023-11-30')
    obs.drop(columns='systime', inplace=True)
    obstats = pd.concat([obstats, obs])
    
    ord = ticker.orderstats(date='2023-11-01', till_date='2023-11-30')
    ord.drop(columns=['systime'], inplace=True)
    orderbook = pd.concat([orderbook, ord])

In [73]:
tradestats.to_csv('backtest_tradestats.csv')
obstats.to_csv('backtest_obstats.csv')
orderbook.to_csv('backtest_orderbook.csv')

In [74]:
tradestats = pd.read_csv('./backtest_tradestats.csv', index_col=0)
tradestats['tradetime'] = tradestats['tradetime'].apply(lambda x: datetime.strptime(x, '%H:%M:%S').time())
tradestats['tradedate'] = tradestats['tradedate'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
for i, r in tradestats.iterrows():
    tradestats.loc[i, 'ts'] = datetime.combine(r.tradedate, r.tradetime)
tradestats.rename(columns={'ticker': 'secid'}, inplace=True)
tradestats.drop(columns=['tradetime', 'tradedate'], inplace=True)

obstats = pd.read_csv('./backtest_obstats.csv', index_col=0)
obstats['tradetime'] = obstats['tradetime'].apply(lambda x: datetime.strptime(x, '%H:%M:%S').time())
obstats['tradedate'] = obstats['tradedate'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
for i, r in obstats.iterrows():
    obstats.loc[i, 'ts'] = datetime.combine(r.tradedate, r.tradetime)
obstats.rename(columns={'ticker': 'secid'}, inplace=True)
obstats.drop(columns=['tradetime', 'tradedate'], inplace=True)

orderbook = pd.read_csv('./backtest_orderbook.csv', index_col=0)
orderbook['tradetime'] = orderbook['tradetime'].apply(lambda x: datetime.strptime(x, '%H:%M:%S').time())
orderbook['tradedate'] = orderbook['tradedate'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
for i, r in orderbook.iterrows():
    orderbook.loc[i, 'ts'] = datetime.combine(r.tradedate, r.tradetime)
orderbook.rename(columns={'ticker': 'secid'}, inplace=True)
orderbook.drop(columns=['tradetime', 'tradedate'], inplace=True)

In [75]:
tradestats.to_csv('backtest_tradestats.csv')
obstats.to_csv('backtest_obstats.csv')
orderbook.to_csv('backtest_orderbook.csv')

In [76]:
tradestats = pd.read_csv('./backtest_tradestats.csv', index_col=0)
tradestats['ts'] = tradestats['ts'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))

In [77]:
tradestats

,secid,pr_open,pr_high,pr_low,pr_close,pr_std,vol,val,trades,pr_vwap,...,trades_b,trades_s,val_b,val_s,vol_b,vol_s,disb,pr_vwap_b,pr_vwap_s,ts
0,AFLT,39.37,39.47,39.37,39.45,0.0004,5749,2266982.0,150,39.43,...,102,48,1295797.0,971185.0,3285,2464,0.14,39.45,39.41,2023-11-01 10:05:00
1,AFLT,39.47,39.61,39.43,39.54,0.0002,21129,8357272.0,298,39.55,...,220,78,6446669.0,1910603.0,16298,4831,0.54,39.55,39.55,2023-11-01 10:10:00
2,AFLT,39.52,39.63,39.52,39.57,0.0002,35966,14235635.0,245,39.58,...,163,82,11016187.0,3219448.0,27836,8130,0.55,39.58,39.60,2023-11-01 10:15:00
3,AFLT,39.57,39.60,39.56,39.57,0.0002,2038,806368.0,89,39.57,...,33,56,91038.0,715329.0,230,1808,-0.77,39.58,39.56,2023-11-01 10:20:00
4,AFLT,39.57,39.60,39.55,39.60,0.0002,19954,7893483.0,141,39.56,...,92,49,930437.0,6963045.0,2350,17604,-0.76,39.59,39.55,2023-11-01 10:25:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2073,MTLR,292.79,293.50,292.76,293.44,0.0001,65829,19290334.0,618,293.04,...,285,333,10785689.0,8504645.0,36809,29020,0.12,293.02,293.06,2023-11-30 18:20:00
2074,MTLR,293.49,294.45,293.49,294.39,0.0002,313094,92051554.0,1496,294.01,...,729,767,47822641.0,44228912.0,162678,150416,0.04,293.97,294.04,2023-11-30 18:25:00
2075,MTLR,294.39,294.73,293.75,293.97,0.0002,213727,62914404.0,1125,294.37,...,551,574,30548619.0,32365785.0,103782,109945,-0.03,294.35,294.38,2023-11-30 18:30:00
2076,MTLR,294.07,294.25,293.60,293.88,0.0002,104256,30641081.0,471,293.90,...,227,244,15559050.0,15082031.0,52938,51318,0.02,293.91,293.89,2023-11-30 18:35:00
2077,MTLR,293.70,293.85,293.16,293.51,0.0002,125338,36789081.0,441,293.52,...,213,228,15836275.0,20952806.0,53949,71389,-0.14,293.54,293.50,2023-11-30 18:40:00

In [78]:
tradestats = pd.DataFrame()
obstats = pd.DataFrame()
orderbook = pd.DataFrame()

for ticker_name in ['AFLT', 'BANE', 'DSKY', 'FEES', 'GAZP', 'PHOR', 'POSI', 'SBER', 'YNDX', 'MTLR']:
    ticker = Ticker(ticker_name)
    
    t = ticker.tradestats(date='2023-10-01', till_date='2023-10-31')
    t.drop(columns='systime', inplace=True)
    tradestats = pd.concat([tradestats, t])

    obs = ticker.obstats(date='2023-10-01', till_date='2023-10-31')
    obs.drop(columns='systime', inplace=True)
    obstats = pd.concat([obstats, obs])
    
    ord = ticker.orderstats(date='2023-10-01', till_date='2023-10-31')
    ord.drop(columns=['systime'], inplace=True)
    orderbook = pd.concat([orderbook, ord])

In [79]:
tradestats.to_csv('backtest_tradestats_2023-10-01_2023-10-31.csv')
obstats.to_csv('backtest_obstats_2023-10-01_2023-10-31.csv')
orderbook.to_csv('backtest_orderbook_2023-10-01_2023-10-31.csv')

In [80]:
tradestats = pd.read_csv('./backtest_tradestats_2023-10-01_2023-10-31.csv', index_col=0)
tradestats['tradetime'] = tradestats['tradetime'].apply(lambda x: datetime.strptime(x, '%H:%M:%S').time())
tradestats['tradedate'] = tradestats['tradedate'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
for i, r in tradestats.iterrows():
    tradestats.loc[i, 'ts'] = datetime.combine(r.tradedate, r.tradetime)
tradestats.rename(columns={'ticker': 'secid'}, inplace=True)
tradestats.drop(columns=['tradetime', 'tradedate'], inplace=True)

obstats = pd.read_csv('./backtest_obstats_2023-10-01_2023-10-31.csv', index_col=0)
obstats['tradetime'] = obstats['tradetime'].apply(lambda x: datetime.strptime(x, '%H:%M:%S').time())
obstats['tradedate'] = obstats['tradedate'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
for i, r in obstats.iterrows():
    obstats.loc[i, 'ts'] = datetime.combine(r.tradedate, r.tradetime)
obstats.rename(columns={'ticker': 'secid'}, inplace=True)
obstats.drop(columns=['tradetime', 'tradedate'], inplace=True)

orderbook = pd.read_csv('./backtest_orderbook_2023-10-01_2023-10-31.csv', index_col=0)
orderbook['tradetime'] = orderbook['tradetime'].apply(lambda x: datetime.strptime(x, '%H:%M:%S').time())
orderbook['tradedate'] = orderbook['tradedate'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
for i, r in orderbook.iterrows():
    orderbook.loc[i, 'ts'] = datetime.combine(r.tradedate, r.tradetime)
orderbook.rename(columns={'ticker': 'secid'}, inplace=True)
orderbook.drop(columns=['tradetime', 'tradedate'], inplace=True)

In [81]:
tradestats.to_csv('backtest_tradestats_2023-10-01_2023-10-31.csv')
obstats.to_csv('backtest_obstats_2023-10-01_2023-10-31.csv')
orderbook.to_csv('backtest_orderbook_2023-10-01_2023-10-31.csv')

In [82]:
tradestats.columns

Index(['secid', 'pr_open', 'pr_high', 'pr_low', 'pr_close', 'pr_std', 'vol',
       'val', 'trades', 'pr_vwap', 'pr_change', 'trades_b', 'trades_s',
       'val_b', 'val_s', 'vol_b', 'vol_s', 'disb', 'pr_vwap_b', 'pr_vwap_s',
       'ts'],
      dtype='object')

In [85]:
obstats.columns

Index(['secid', 'spread_bbo', 'spread_lv10', 'spread_1mio', 'levels_b',
       'levels_s', 'vol_b', 'vol_s', 'val_b', 'val_s', 'imbalance_vol_bbo',
       'imbalance_val_bbo', 'imbalance_vol', 'imbalance_val', 'vwap_b',
       'vwap_s', 'vwap_b_1mio', 'vwap_s_1mio', 'ts'],
      dtype='object')

In [84]:
orderbook.columns

Index(['secid', 'put_orders_b', 'put_orders_s', 'put_val_b', 'put_val_s',
       'put_vol_b', 'put_vol_s', 'put_vwap_b', 'put_vwap_s', 'put_vol',
       'put_val', 'put_orders', 'cancel_orders_b', 'cancel_orders_s',
       'cancel_val_b', 'cancel_val_s', 'cancel_vol_b', 'cancel_vol_s',
       'cancel_vwap_b', 'cancel_vwap_s', 'cancel_vol', 'cancel_val',
       'cancel_orders', 'ts'],
      dtype='object')